### ISSUE TITLE
Get verification on Flathub

### ISSUE THREAD

**Issue by rashidi77** [flathub/io.github.dbchoco.muezzin#4]
You can now get verified badge for your apps on Flathub beta frontend using your Github account or your project website. There is already 100+ verified apps on Flathub including Firefox, Telegram, OBS and LibreOffice. Many more small apps also got their verified badge.

**Comment by DBChoco** [comment]
Assalam Alaykoum,

Jazzaka Lahu khairan for letting me know, I went right away to do it and inshaAllah it should take effect soon.

![image](https://user-images.githubusercontent.com/44785461/220390818-6c23d354-a356-49e0-9a72-6544f684f688.png)

I'll close the issue as soon as the "Verified" sign appears.

Assalam Alaykum wa Rahmatou Lahi wa Baraketu

**Comment by DBChoco** [comment]
Done, Jazzaka Lahu khairan once again!

![image](https://user-images.githubusercontent.com/44785461/220422331-7b85e956-a8bc-4078-898b-ed153fa9e958.png)
